### ISSUE TITLE
AttributeError: 'AxesSubplot' object has no attribute 'set_axis_bgcolor'

### ISSUE THREAD

**Issue by PhilippSchaad** [djordon/queueing-tool#51]
Drawing a queueing network results in pyplot (matplotlib) throwing the following exception:

    Traceback (most recent call last):
      File "scripts/data_processing/07_queue_net.py", line 39, in <module>
        network.draw(figsize=(12, 2))
      File "/usr/local/lib/python3.6/dist-packages/queueing_tool/network/queue_network.py", line 735, in draw
        scatter_kwargs=scatter_kwargs, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/queueing_tool/graph/graph_wrapper.py", line 414, in draw_graph
        ax.set_axis_bgcolor(kwargs.get('bgcolor', [1, 1, 1, 1]))
    AttributeError: 'AxesSubplot' object has no attribute 'set_axis_bgcolor' 

It looks like `set_axis_bgcolor` was replaced with `set_facecolor` ([source](https://github.com/scikit-learn/scikit-learn/issues/10762))

**Comment by djordon** [comment]
Ahhh I see. Okay, I'll take a look and release a fix for this. Thanks for reporting

**Comment by djordon** [comment]
@PhilippSchaad I just uploaded an updated version of queueing-tool to pypi. Let me know if find anymore issues

**Comment by PhilippSchaad** [comment]
@djordon Perfect, it works as expected now! Thanks!
